server:
  port: ${SERVER_PORT:8080}
  context-path: /transaction-practice
  display-name: transaction-practice
spring:
  datasource:
     type: com.zaxxer.hikari.HikariDataSource
     driver-class-name: com.mysql.jdbc.Driver
     url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8}
     username: ${DATASOURCE_USERNAME:transaction}
     password: ${DATASOURCE_PASSWORD:123qwe_+}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect